### ISSUE TITLE
Missing some urls in dataLink column

### ISSUE THREAD

**Issue by theoryshaw** [agbilotia1998/dropbox-event-scraper#3]
Hi @agbilotia1998,

I noticed on the 'dataLink' column, that it misses events like the following example. 

![image](https://user-images.githubusercontent.com/507113/111394950-bd546b80-8689-11eb-8abc-58b2dc27d131.png)

The intent was for it to pick up the 1st link that shows up in that list.  In this example, it's the one circled in blue. 

Is there a way you can tweak this script to pick those up?

**Comment by agbilotia1998** [comment]
Hi @theoryshaw I will check this and get back to you!

**Comment by agbilotia1998** [comment]
Hi @theoryshaw sent you an email regarding some required details.

**Comment by theoryshaw** [comment]
Hi Ayush, for for the delay, just emailed them.

**Comment by agbilotia1998** [comment]
Hi @theoryshaw sorry got busy somewhere, I've pushed a fix, please check and let me know if it works. Thanks :)

**Comment by agbilotia1998** [comment]
Closing this. Thanks @theoryshaw!
